weights: runs_ccpd/train/exp/weights/last.pt
cfg: ''
data: ccpd/cfg/ccpd.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 72
img_size:
- 320
- 320
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs_ccpd/train
name: exp
exist_ok: false
total_batch_size: 72
world_size: 1
global_rank: -1
save_dir: runs_ccpd/train/exp
